dist: trusty
language: node_js
node_js:
  - 10.16.3
addons:
  chrome: stable
notifications:
  email: false
cache:
  directories:
    - node_modules
sudo: required

install:
  - npm i

script:
  - npm run test

env:
  global:
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    - TEST_HOST_STORYBOOK_PORT=9999
    - TEST_HOST_STORYBOOK_URL=http://localhost:9999
